# 레모네이드 판매예측
## deep learning 기초 1

In [3]:
# 1. 라이브러리 불러오기
import tensorflow as tf
import pandas as pd

In [6]:
# 2. 파일 불러오기 / 영어만인지, 한글 포함인지 조심(utf-8)
file_path = './lemonade1-1_E.csv'
data = pd.read_csv(file_path) # 변수명 주의
data.head()

TEMP  SALES
0    20     40
1    21     42
2    22     44
3    23     46
4    24     48

In [7]:
# 3. # 파일 데이터 분리 (독립 = indeopen, 종속 = deopen)
indeopen = data[['TEMP']] # 독립 변수
deopen = data[['SALES']] # 종속 변수
print(indeopen.shape, deopen.shape)

(6, 1) (6, 1)


In [9]:
# 4. 모델 만들기
X = tf.keras.layers.Input(shape=[1])
Y = tf.keras.layers.Dense(1)(X)

model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [11]:
# 5. 모델 학습 (FIT)
model.fit(indeopen, deopen, epochs=3000) # 3000번 학습

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
1/1 [==============================] - 0s 9ms/step - loss: 2518.1750
Epoch 502/3000
1/1 [==============================] - 0s 9ms/step - loss: 2515.8210
Epoch 503/3000
1/1 [==============================] - 0s 13ms/step - loss: 2513.4678
Epoch 504/3000
1/1 [==============================] - 0s 9ms/step - loss: 2511.1160
Epoch 505/3000
1/1 [==============================] - 0s 9ms/step - loss: 2508.7649
Epoch 506/3000
1/1 [==============================] - 0s 11ms/step - loss: 2506.4150
Epoch 507/3000
1/1 [==============================] - 0s 9ms/step - loss: 2504.0662
Epoch 508/3000
1/1 [==============================] - 0s 10ms/step - loss: 2501.7188
Epoch 509/3000
1/1 [==============================] - 0s 9ms/step - loss: 2499.3723
Epoch 510/3000
1/1 [==============================] - 0s 9ms/step - loss: 2497.0269
Epoch 511/3000
1/1 [==============================] - 0s 8ms/step - loss: 2494.6826
Epoch 512/3000
1/1 [==============================] 

In [12]:
# loss = 0.0116 ... 나쁘지 않음 => 0.0002 )
model.predict(indeopen)

1/1 [==============================] - 0s 80ms/step


array([[40.30186 ],
       [42.191334],
       [44.080807],
       [45.97028 ],
       [47.859753],
       [49.749226]], dtype=float32)

In [13]:
# 우리가 예측하고 싶은 값을 넣음 1
model.predict([[15]])

1/1 [==============================] - 0s 36ms/step


array([[30.854496]], dtype=float32)

In [14]:
# 우리가 예측하고 싶은 값을 넣음 2
model.predict([[30]])

1/1 [==============================] - 0s 37ms/step


array([[59.19659]], dtype=float32)

In [15]:
# 우리가 예측하고 싶은 값을 넣음 3
model.predict([[21.5]])

1/1 [==============================] - 0s 75ms/step


array([[43.13607]], dtype=float32)